# Generated by Django 5.1.3 on 2026-09-14 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('note', models.TextField(blank=True, help_text='Например: координаты вымышлены для демонстрации.', verbose_name='Примечание')),
                ('is_demo', models.BooleanField(default=True, verbose_name='Демонстрационные данные')),
                ('boundary_geojson', models.JSONField(help_text='{"type": "Polygon", "coordinates": [[[lon, lat], ...]]}', verbose_name='Граница площадки (GeoJSON Polygon)')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=500, verbose_name='Путь к файлу снимка')),
                ('image_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 снимка')),
                ('observed_date', models.DateField(blank=True, null=True, verbose_name='Дата съёмки')),
                ('date_confirmed', models.BooleanField(default=False, verbose_name='Дата подтверждена')),
                ('overall_status', models.CharField(choices=[('no_deviation', 'Отклонений не выявлено'), ('possible_deviation', 'Возможное отклонение'), ('insufficient_data', 'Недостаточно данных')], max_length=24, verbose_name='Итоговый статус')),
                ('overall_explanation', models.TextField(verbose_name='Объяснение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Наблюдение (анализ снимка)',
                'verbose_name_plural': 'Наблюдения (история анализа)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SlugField(max_length=64, unique=True, verbose_name='Идентификатор этапа')),
                ('work_code', models.CharField(blank=True, help_text='Код из works_catalog.csv, если есть свой; иначе — код родителя.', max_length=32, verbose_name='Код работы (справочник)')),
                ('work_name', models.CharField(max_length=300, verbose_name='Наименование работы')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('technology_assumption', models.TextField(blank=True, help_text='Один из возможных вариантов технологии — не единственно допустимый.', verbose_name='Технологическое допущение')),
                ('is_demo', models.BooleanField(default=True, verbose_name='Демонстрационные даты')),
            ],
            options={
                'verbose_name': 'Этап графика',
                'verbose_name_plural': 'Этапы графика',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='Ключ класса')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Название по-русски')),
                ('prompts', models.JSONField(default=list, help_text='Список строк, например ["excavator", "crawler excavator"].', verbose_name='Текстовые промпты (англ.)')),
                ('in_taxonomy', models.BooleanField(default=True, help_text='Выключено — вспомогательный класс-«отвлекающий» (человек, легковой автомобиль).', verbose_name='Входит в таксономию ТЗ')),
            ],
            options={
                'verbose_name': 'Класс техники',
                'verbose_name_plural': 'Словарь классов техники',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_key', models.CharField(max_length=64, verbose_name='Класс (ключ)')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Класс (по-русски)')),
                ('in_taxonomy', models.BooleanField(default=True, verbose_name='Входит в таксономию')),
                ('confidence', models.FloatField(verbose_name='Уверенность')),
                ('bbox', models.JSONField(verbose_name='Рамка [x1, y1, x2, y2]')),
                ('ambiguous', models.BooleanField(default=False, verbose_name='Неоднозначная классификация')),
                ('runner_up_class_key', models.CharField(blank=True, max_length=64, verbose_name='Альтернативный класс (при неоднозначности)')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.observation', verbose_name='Наблюдение')),
            ],
            options={
                'verbose_name': 'Детекция',
                'verbose_name_plural': 'Детекции',
            },
        ),
        migrations.CreateModel(
            name='StageEvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name_snapshot', models.CharField(max_length=300, verbose_name='Название этапа на момент проверки')),
                ('status', models.CharField(choices=[('no_deviation', 'Отклонений не выявлено'), ('possible_deviation', 'Возможное отклонение'), ('insufficient_data', 'Недостаточно данных')], max_length=24, verbose_name='Статус')),
                ('explanation', models.TextField(verbose_name='Объяснение')),
                ('required_snapshot', models.JSONField(default=list, verbose_name='Требуемая техника (снимок)')),
                ('allowed_snapshot', models.JSONField(default=list, verbose_name='Допустимая техника (снимок)')),
                ('missing_required', models.JSONField(default=list, verbose_name='Отсутствующая техника')),
                ('unexpected_detections', models.JSONField(default=list, verbose_name='Неожиданная техника')),
                ('ambiguous_detections', models.JSONField(default=list, verbose_name='Неоднозначные детекции')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_evaluations', to='core.observation', verbose_name='Наблюдение')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='core.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Результат проверки этапа',
                'verbose_name_plural': 'Результаты проверки этапов',
            },
        ),
        migrations.CreateModel(
            name='StageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatives_note', models.TextField(blank=True, help_text='Например: другая согласованная технология не считается нарушением.', verbose_name='Примечание об альтернативах')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='core.stage', verbose_name='Этап')),
                ('allowed', models.ManyToManyField(blank=True, related_name='allowed_for_rules', to='core.vocabularyclass', verbose_name='Допустимая техника')),
                ('required', models.ManyToManyField(blank=True, related_name='required_for_rules', to='core.vocabularyclass', verbose_name='Обязательная техника')),
            ],
            options={
                'verbose_name': 'Правило техники для этапа',
                'verbose_name_plural': 'Правила техники по этапам',
            },
        ),
        migrations.CreateModel(
            name='KnownLimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('low_precision', 'Низкая точность'), ('low_recall', 'Низкая полнота')], max_length=20, verbose_name='Тип проблемы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('vocabulary_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_limitations', to='core.vocabularyclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Известное ограничение',
                'verbose_name_plural': 'Известные ограничения',
            },
        ),
        migrations.CreateModel(
            name='WeatherRiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='open-meteo', max_length=64, verbose_name='Источник')),
                ('factor', models.CharField(max_length=32, verbose_name='Фактор')),
                ('comparison', models.CharField(max_length=8, verbose_name='Сравнение')),
                ('threshold', models.FloatField(verbose_name='Порог')),
                ('units', models.CharField(blank=True, max_length=16, verbose_name='Единицы')),
                ('start_time_utc', models.DateTimeField(verbose_name='Начало периода (UTC)')),
                ('end_time_utc', models.DateTimeField(verbose_name='Окончание периода (UTC)')),
                ('peak_value', models.FloatField(verbose_name='Пиковое значение')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_risk_records', to='core.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Погодный риск (история)',
                'verbose_name_plural': 'Погодные риски (история)',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(choices=[('temperature_2m', 'Температура'), ('precipitation', 'Осадки'), ('precipitation_probability', 'Вероятность осадков'), ('wind_speed_10m', 'Скорость ветра'), ('wind_gusts_10m', 'Порывы ветра')], max_length=32, verbose_name='Фактор')),
                ('comparison', models.CharField(choices=[('gte', 'не меньше (≥)'), ('lte', 'не больше (≤)')], max_length=8, verbose_name='Сравнение')),
                ('threshold', models.FloatField(verbose_name='Порог')),
                ('units', models.CharField(blank=True, max_length=16, verbose_name='Единицы')),
                ('message', models.TextField(verbose_name='Сообщение для инженера')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_rules', to='core.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Погодное правило',
                'verbose_name_plural': 'Погодные правила',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SlugField(help_text='Используется в API и на фронтенде, например "zone-a".', max_length=64, unique=True, verbose_name='Идентификатор зоны')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('geometry_geojson', models.JSONField(help_text='{"type": "Polygon", "coordinates": [[[lon, lat], ...]]}', verbose_name='Геометрия зоны (GeoJSON Polygon)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.constructionsite', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.zone', verbose_name='Зона'),
        ),
        migrations.AddField(
            model_name='observation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.zone', verbose_name='Зона'),
        ),
        migrations.CreateModel(
            name='ConfusablePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_note', models.TextField(blank=True, help_text='Например: ссылка на конкретный снимок из val-выборки.', verbose_name='Обоснование')),
                ('class_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusable_as_a', to='core.vocabularyclass', verbose_name='Класс А')),
                ('class_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusable_as_b', to='core.vocabularyclass', verbose_name='Класс Б')),
            ],
            options={
                'verbose_name': 'Путаемая пара классов',
                'verbose_name_plural': 'Путаемые пары классов',
                'unique_together': {('class_a', 'class_b')},
            },
        ),
    ]
