# Generated by Django 5.1.3 on 2026-09-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiguity_margin', models.FloatField(default=0.15, help_text='Справочно: для известных confusable-пар результат всегда считается неоднозначным независимо от confidence (см. detector.py) — это поле сейчас хранится для справки и будущей калибровки.', verbose_name='Порог неоднозначности')),
            ],
            options={
                'verbose_name': 'Настройки сопоставления',
                'verbose_name_plural': 'Настройки сопоставления',
            },
        ),
    ]
