# Generated by Django 5.1.3 on 2026-09-16 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matchingsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stageevaluationrecord',
            name='quantity_checks_snapshot',
            field=models.JSONField(default=list, help_text='[{"class_key", "label_ru", "required_qty", "actual_qty", "satisfied"}, ...]', verbose_name='План/факт по количеству (снимок)'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SlugField(max_length=64, unique=True, verbose_name='Идентификатор камеры')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('is_demo', models.BooleanField(default=True, verbose_name='Демонстрационные данные')),
                ('note', models.TextField(blank=True, help_text='Например: координаты — центроид зоны, а не реальное расположение камеры.', verbose_name='Примечание')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='core.zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.RemoveField(
            model_name='stagerule',
            name='required',
        ),
        migrations.CreateModel(
            name='StageRequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Минимальное количество')),
                ('stage_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='core.stagerule', verbose_name='Правило')),
                ('vocabulary_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='core.vocabularyclass', verbose_name='Класс техники')),
            ],
            options={
                'verbose_name': 'Обязательная техника (количество)',
                'verbose_name_plural': 'Обязательная техника (количества)',
                'unique_together': {('stage_rule', 'vocabulary_class')},
            },
        ),
        migrations.AddField(
            model_name='stagerule',
            name='required',
            field=models.ManyToManyField(blank=True, related_name='required_for_rules', through='core.StageRequiredItem', to='core.vocabularyclass', verbose_name='Обязательная техника'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('participant', 'Участник проекта')], default='participant', max_length=16, verbose_name='Роль')),
                ('position', models.CharField(blank=True, help_text='Отображается в шапке интерфейса под именем, например «Руководитель проекта».', max_length=150, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
