# Generated by Django 5.1.3 on 2026-09-16 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stageevaluationrecord_quantity_checks_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_image_path', models.CharField(max_length=500, verbose_name='Путь к обрезанному фрагменту')),
                ('bbox', models.JSONField(default=list, verbose_name='Рамка [x1, y1, x2, y2] на исходном снимке')),
                ('original_class_key', models.CharField(blank=True, max_length=64, verbose_name='Исходный класс (по версии детектора)')),
                ('original_confidence', models.FloatField(blank=True, null=True, verbose_name='Исходная уверенность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('corrected_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='core.vocabularyclass', verbose_name='Исправленный класс (пусто — «не техника»)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to=settings.AUTH_USER_MODEL, verbose_name='Автор коррекции')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='core.observation', verbose_name='Наблюдение')),
            ],
            options={
                'verbose_name': 'Коррекция',
                'verbose_name_plural': 'Коррекции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=32, verbose_name='Версия')),
                ('status', models.CharField(choices=[('candidate', 'Кандидат'), ('production', 'Рабочая версия'), ('archived', 'Архив')], default='candidate', max_length=16, verbose_name='Статус')),
                ('artifact_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к артефакту классификатора')),
                ('trained_at', models.DateTimeField(blank=True, null=True, verbose_name='Обучена')),
                ('training_sample_count', models.PositiveIntegerField(default=0, verbose_name='Число коррекций, использованных при обучении')),
                ('metrics_json', models.JSONField(blank=True, default=dict, help_text='{"available": bool, "train_count", "test_count", "accuracy", "per_class": [...]}', verbose_name='Метрики (измеренные на отложенной части коррекций)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='core.modelversion', verbose_name='Предыдущая версия')),
            ],
            options={
                'verbose_name': 'Версия модели-корректора',
                'verbose_name_plural': 'Версии модели-корректора',
                'ordering': ['-created_at'],
            },
        ),
    ]
