# Generated by Django 5.1.3 on 2026-09-25 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projects_and_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingsettings',
            name='autolabel_min_vlm_confidence',
            field=models.CharField(choices=[('high', 'Только высокая'), ('medium', 'Высокая и средняя'), ('low', 'Любая')], default='high', help_text='Какой уверенности модели достаточно, чтобы принять класс фрагмента в разметку. «Только высокая» даёт меньше рамок, но меньше ошибок вроде «провод — это рукав бетононасоса» или «легковая машина — это грузовик».', max_length=8, verbose_name='Минимальная уверенность при авторазметке'),
        ),
        migrations.AddField(
            model_name='matchingsettings',
            name='detector_confidence',
            field=models.FloatField(default=0.25, help_text='Рамки с меньшей уверенностью отбрасываются при анализе снимка. Ниже порог — больше находок и больше ложных срабатываний, выше — наоборот. Допустимый диапазон 0.05-0.95.', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.95)], verbose_name='Порог уверенности детектора'),
        ),
    ]
