# Generated by Django 5.1.3 on 2026-09-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_settings_confidence_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='activity',
            field=models.CharField(choices=[('working', 'Работает'), ('idle', 'Простаивает'), ('unknown', 'Определить нельзя')], default='unknown', max_length=8, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='detection',
            name='activity_reason',
            field=models.CharField(blank=True, help_text='Почему техника считается работающей или простаивающей — для объяснения инженеру.', max_length=300, verbose_name='Обоснование активности'),
        ),
        migrations.CreateModel(
            name='FrameZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('kind', models.CharField(choices=[('work', 'Рабочая зона'), ('parking', 'Стоянка и отстой техники'), ('entrance', 'Въезд и выезд'), ('danger', 'Опасная зона'), ('uncontrolled', 'Вне контроля')], default='work', max_length=16, verbose_name='Тип зоны')),
                ('polygon', models.JSONField(help_text='Список точек [[x, y], ...] в координатах опорного кадра, минимум три точки.', verbose_name='Полигон в пикселях кадра')),
                ('reference_width', models.PositiveIntegerField(help_text='Размер снимка, на котором рисовалась зона. Нужен, чтобы пересчитать координаты, если камера прислала кадр другого разрешения.', verbose_name='Ширина опорного кадра')),
                ('reference_height', models.PositiveIntegerField(verbose_name='Высота опорного кадра')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_zones', to='core.camera', verbose_name='Камера')),
                ('stage', models.ForeignKey(blank=True, help_text='Для рабочей зоны: какой этап ведётся именно здесь.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_zones', to='core.stage', verbose_name='Этап графика')),
            ],
            options={
                'verbose_name': 'Зона на кадре',
                'verbose_name_plural': 'Зоны на кадре',
                'ordering': ['camera', 'kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='frame_zone',
            field=models.ForeignKey(blank=True, help_text='Зона, в которую попадает нижняя точка рамки (точка опоры машины).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='core.framezone', verbose_name='Зона на кадре'),
        ),
    ]
