# Generated by Django 5.1.3 on 2026-09-25 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_frame_zones_and_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='Без привязки к камере невозможно ни применить зоны кадра, ни сравнить снимок с предыдущими: кадры разных камер несопоставимы попиксельно.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='core.camera', verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='observation',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота снимка'),
        ),
        migrations.AddField(
            model_name='observation',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина снимка'),
        ),
    ]
