# Generated by Django 5.1.3 on 2026-09-25 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_observation_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Укрупнённая работа или веха, в которую входит этот этап.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.stage', verbose_name='Родительская работа'),
        ),
        migrations.AddField(
            model_name='stage',
            name='predecessors',
            field=models.ManyToManyField(blank=True, help_text='Работы, которые должны завершиться до начала этой — связь «окончание-начало». На них строится расчёт критического пути.', related_name='successors', to='core.stage', verbose_name='Предшественники'),
        ),
    ]
