# Generated by Django 5.1.3 on 2026-09-25 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stage_parent_stage_predecessors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('missing_equipment', 'Нет требуемой техники'), ('quantity_shortfall', 'Техники меньше плана'), ('unexpected_equipment', 'Посторонняя техника'), ('equipment_idle', 'Простой техники'), ('equipment_in_danger_zone', 'Техника в опасной зоне'), ('equipment_out_of_work_zone', 'Техника вне рабочей зоны'), ('zone_not_covered', 'Зона вне контроля камер'), ('stage_mismatch', 'Стадия на снимке не совпадает с графиком')], max_length=32, verbose_name='Тип')),
                ('severity', models.CharField(choices=[('critical', 'Критично'), ('warning', 'Требует внимания'), ('info', 'К сведению')], default='warning', max_length=16, verbose_name='Важность')),
                ('status', models.CharField(choices=[('detected', 'Выявлено'), ('assigned', 'Назначено'), ('resolved', 'Устранено'), ('confirmed', 'Подтверждено'), ('dismissed', 'Ложное срабатывание')], default='detected', max_length=16, verbose_name='Состояние')),
                ('signature', models.CharField(db_index=True, help_text='Устойчивый ключ (зона + этап + тип + состав техники). По нему система понимает, что на новом снимке то же самое нарушение, а не новое.', max_length=300, verbose_name='Ключ совпадения')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Описание')),
                ('equipment', models.JSONField(blank=True, default=list, verbose_name='Затронутая техника')),
                ('is_on_critical_path', models.BooleanField(default=False, help_text='Отклонение по такому этапу напрямую сдвигает дату сдачи объекта.', verbose_name='На критическом пути')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='Сколько снимков подтвердили')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Комментарий при закрытии')),
                ('auto_resolved', models.BooleanField(default=False, help_text='На следующем снимке зоны отклонение больше не воспроизвелось.', verbose_name='Закрыто автоматически')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Выявлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Устранено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deviations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('first_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_opened', to='core.observation', verbose_name='Снимок «до» (выявлено)')),
                ('last_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_seen', to='core.observation', verbose_name='Последний снимок с этим отклонением')),
                ('resolved_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_closed', to='core.observation', verbose_name='Снимок «после» (устранено)')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='core.stage', verbose_name='Этап графика')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='core.zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Отклонение',
                'verbose_name_plural': 'Отклонения',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('observation_analyzed', 'Снимок проанализирован'), ('deviation_detected', 'Отклонение выявлено'), ('deviation_repeated', 'Отклонение повторилось'), ('deviation_status_changed', 'Состояние отклонения изменено'), ('deviation_auto_resolved', 'Отклонение закрыто по следующему снимку')], max_length=32, verbose_name='Тип события')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Описание')),
                ('old_value', models.CharField(blank=True, max_length=100, verbose_name='Было')),
                ('new_value', models.CharField(blank=True, max_length=100, verbose_name='Стало')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(blank=True, help_text='Пусто — событие создано системой по результату анализа снимка.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто сделал')),
                ('deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.deviation', verbose_name='Отклонение')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.observation', verbose_name='Наблюдение')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.constructionsite', verbose_name='Проект')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Событие проекта',
                'verbose_name_plural': 'Лента событий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deviation',
            index=models.Index(fields=['zone', 'status'], name='core_deviat_zone_id_3e7a01_idx'),
        ),
    ]
