# Generated by Django 5.1.3 on 2026-09-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deviation_projectevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='external_key',
            field=models.SlugField(blank=True, default='', help_text='Заполняется только у объектов, загруженных командой импорта. Нужен, чтобы повторный импорт обновлял тот же объект, а не плодил дубликаты по названию.', max_length=64, verbose_name='Ключ импорта'),
        ),
    ]
