# Generated by Django 5.1.3 on 2026-09-25 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_constructionsite_external_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='readiness_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто — модель не смогла оценить готовность по этому кадру.', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Готовность объекта по снимку, %'),
        ),
        migrations.AddField(
            model_name='observation',
            name='vision_stage_key',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Стадия по снимку (ключ)'),
        ),
        migrations.AddField(
            model_name='observation',
            name='vision_stage_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Стадия по снимку'),
        ),
    ]
