# Generated by Django 5.1.3 on 2026-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_observation_readiness_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_path',
            field=models.CharField(blank=True, default='', help_text='Абсолютный путь на диске (data/uploads/avatars/...), не URL — отдаётся через отдельный эндпоинт FastAPI.', max_length=500, verbose_name='Путь к файлу аватара'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, help_text='Отображается в шапке интерфейса под именем, например «Ruководитель проекта».', max_length=150, verbose_name='Должность'),
        ),
    ]
