# Generated by Django 5.2.5 on 2026-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_avatar_path_alter_userprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='stream_url',
            field=models.URLField(blank=True, default='', help_text='Просто внешняя ссылка для просмотра (например, YouTube-трансляция). Система не обрабатывает сам видеопоток и не анализирует его кадры — только фотографии.', verbose_name='Ссылка на видеотрансляцию'),
        ),
    ]
