# Generated by Django 5.1.3 on 2026-09-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_constructionsite_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.URLField(blank=True, default='', help_text='Просто внешняя ссылка для просмотра этой конкретной камеры. Система не обрабатывает сам поток и не анализирует его кадры — только фотографии.', verbose_name='Ссылка на видеотрансляцию'),
        ),
    ]
