# Generated by Django 5.2.5 on 2026-09-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_camera_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='kind',
            field=models.CharField(choices=[('work', 'Рабочая зона'), ('parking', 'Стоянка и отстой техники'), ('entrance', 'Въезд и выезд'), ('danger', 'Опасная зона'), ('uncontrolled', 'Вне контроля')], default='work', help_text='Справочный тип для карты площадки (не влияет на проверку техники по графику — та логика работает через отдельные зоны кадра камеры, см. FrameZone).', max_length=16, verbose_name='Тип зоны'),
        ),
    ]
