"""
Django settings for admin_panel project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Локальные переменные окружения из .env (в Docker файла нет — загрузчик молчит).
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))
import env_loader  # noqa: F401  (импорт ради побочного эффекта загрузки .env)

# Прототип для хакатона/локальной разработки — не для продакшена без дополнительного ужесточения.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-l!i)382#*%@)se$zgb-qt)e#969kbzc5(4e2_gvj#jiz)_26vo',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Общий cookie сессии для основного домена и его поддомена admin (см. backend/app/auth.py) —
# пусто в локальной разработке (один хост, cookie без явного domain и так работает).
SESSION_COOKIE_DOMAIN = os.environ.get('SK_SESSION_COOKIE_DOMAIN') or None
SESSION_COOKIE_SECURE = os.environ.get('SK_SESSION_COOKIE_SECURE', 'false').lower() == 'true'
SESSION_COOKIE_SAMESITE = 'None' if SESSION_COOKIE_SECURE else 'Lax'
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
# В продакшне задайте DJANGO_CSRF_TRUSTED_ORIGINS через .env (см. .env.example) —
# свой домен и его www-поддомен через запятую.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173',
    ).split(',')
    if origin.strip()
]
# Порты приложений доступны только локально; nginx передаёт исходную HTTPS-схему.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'admin_panel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin_panel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# Целевая СУБД — PostgreSQL: именно она поднимается в docker-compose и используется
# при развёртывании. Для локальной разработки без Docker допускается SQLite:
# DATABASE_URL=sqlite:///относительный/путь.sqlite3 или sqlite:////абсолютный/путь.
# Схема и миграции одни и те же, поэтому расхождения с продакшеном не возникает;
# отличия СУБД важны только для проверки перед деплоем — её делаем через Docker.
_database_url = os.environ.get(
    'DATABASE_URL',
    'postgres://stroykontrol:stroykontrol@localhost:5432/stroykontrol',
)
_parsed_db_url = urlparse(_database_url)

if _parsed_db_url.scheme.startswith('sqlite'):
    # sqlite:///data/local.sqlite3 — путь относительно корня репозитория.
    _sqlite_path = Path((_parsed_db_url.netloc + _parsed_db_url.path).lstrip('/'))
    if not _sqlite_path.is_absolute():
        _sqlite_path = BASE_DIR / _sqlite_path
    _sqlite_path.parent.mkdir(parents=True, exist_ok=True)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(_sqlite_path),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (_parsed_db_url.path or '/stroykontrol').lstrip('/'),
            'USER': _parsed_db_url.username or 'stroykontrol',
            'PASSWORD': _parsed_db_url.password or 'stroykontrol',
            'HOST': _parsed_db_url.hostname or 'localhost',
            'PORT': _parsed_db_url.port or 5432,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
